<?php
/**
 * ElasticMember
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Congressus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@congressus.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Compucie\Congressus\Model;

use \ArrayAccess;
use \Compucie\Congressus\ObjectSerializer;

/**
 * ElasticMember Class Doc Comment
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ElasticMember implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ElasticMember';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        '_score' => 'int',
        'id' => 'int',
        'value' => 'mixed',
        'name' => 'mixed',
        'username' => 'string',
        'type' => 'mixed',
        'email' => 'string',
        'phone_mobile' => 'string',
        'phone_home' => 'string',
        'address' => 'string',
        'zip' => 'string',
        'city' => 'string',
        'province' => 'string',
        'country_id' => 'int',
        'country' => 'string',
        'membership_start' => '\DateTime',
        'membership_end' => '\DateTime',
        'current_member_status_name' => 'string',
        'current_member_status_id' => 'int',
        'manager_uri' => 'mixed'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        '_score' => null,
        'id' => null,
        'value' => null,
        'name' => null,
        'username' => null,
        'type' => null,
        'email' => null,
        'phone_mobile' => null,
        'phone_home' => null,
        'address' => null,
        'zip' => null,
        'city' => null,
        'province' => null,
        'country_id' => null,
        'country' => null,
        'membership_start' => 'date',
        'membership_end' => 'date',
        'current_member_status_name' => null,
        'current_member_status_id' => null,
        'manager_uri' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        '_score' => false,
        'id' => false,
        'value' => true,
        'name' => true,
        'username' => false,
        'type' => true,
        'email' => false,
        'phone_mobile' => false,
        'phone_home' => false,
        'address' => false,
        'zip' => false,
        'city' => false,
        'province' => false,
        'country_id' => false,
        'country' => false,
        'membership_start' => false,
        'membership_end' => false,
        'current_member_status_name' => false,
        'current_member_status_id' => false,
        'manager_uri' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_score' => '_score',
        'id' => 'id',
        'value' => 'value',
        'name' => 'name',
        'username' => 'username',
        'type' => 'type',
        'email' => 'email',
        'phone_mobile' => 'phone_mobile',
        'phone_home' => 'phone_home',
        'address' => 'address',
        'zip' => 'zip',
        'city' => 'city',
        'province' => 'province',
        'country_id' => 'country_id',
        'country' => 'country',
        'membership_start' => 'membership_start',
        'membership_end' => 'membership_end',
        'current_member_status_name' => 'current_member_status_name',
        'current_member_status_id' => 'current_member_status_id',
        'manager_uri' => 'manager_uri'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_score' => 'setScore',
        'id' => 'setId',
        'value' => 'setValue',
        'name' => 'setName',
        'username' => 'setUsername',
        'type' => 'setType',
        'email' => 'setEmail',
        'phone_mobile' => 'setPhoneMobile',
        'phone_home' => 'setPhoneHome',
        'address' => 'setAddress',
        'zip' => 'setZip',
        'city' => 'setCity',
        'province' => 'setProvince',
        'country_id' => 'setCountryId',
        'country' => 'setCountry',
        'membership_start' => 'setMembershipStart',
        'membership_end' => 'setMembershipEnd',
        'current_member_status_name' => 'setCurrentMemberStatusName',
        'current_member_status_id' => 'setCurrentMemberStatusId',
        'manager_uri' => 'setManagerUri'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_score' => 'getScore',
        'id' => 'getId',
        'value' => 'getValue',
        'name' => 'getName',
        'username' => 'getUsername',
        'type' => 'getType',
        'email' => 'getEmail',
        'phone_mobile' => 'getPhoneMobile',
        'phone_home' => 'getPhoneHome',
        'address' => 'getAddress',
        'zip' => 'getZip',
        'city' => 'getCity',
        'province' => 'getProvince',
        'country_id' => 'getCountryId',
        'country' => 'getCountry',
        'membership_start' => 'getMembershipStart',
        'membership_end' => 'getMembershipEnd',
        'current_member_status_name' => 'getCurrentMemberStatusName',
        'current_member_status_id' => 'getCurrentMemberStatusId',
        'manager_uri' => 'getManagerUri'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('_score', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('phone_mobile', $data ?? [], null);
        $this->setIfExists('phone_home', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('zip', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('province', $data ?? [], null);
        $this->setIfExists('country_id', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('membership_start', $data ?? [], null);
        $this->setIfExists('membership_end', $data ?? [], null);
        $this->setIfExists('current_member_status_name', $data ?? [], null);
        $this->setIfExists('current_member_status_id', $data ?? [], null);
        $this->setIfExists('manager_uri', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _score
     *
     * @return int|null
     */
    public function getScore()
    {
        return $this->container['_score'];
    }

    /**
     * Sets _score
     *
     * @param int|null $_score _score
     *
     * @return self
     */
    public function setScore($_score)
    {
        if (is_null($_score)) {
            throw new \InvalidArgumentException('non-nullable _score cannot be null');
        }
        $this->container['_score'] = $_score;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets value
     *
     * @return mixed|null
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param mixed|null $value value
     *
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            array_push($this->openAPINullablesSetToNull, 'value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets name
     *
     * @return mixed|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param mixed|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username username
     *
     * @return self
     */
    public function setUsername($username)
    {
        if (is_null($username)) {
            throw new \InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets type
     *
     * @return mixed|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param mixed|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            array_push($this->openAPINullablesSetToNull, 'type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets phone_mobile
     *
     * @return string|null
     */
    public function getPhoneMobile()
    {
        return $this->container['phone_mobile'];
    }

    /**
     * Sets phone_mobile
     *
     * @param string|null $phone_mobile phone_mobile
     *
     * @return self
     */
    public function setPhoneMobile($phone_mobile)
    {
        if (is_null($phone_mobile)) {
            throw new \InvalidArgumentException('non-nullable phone_mobile cannot be null');
        }
        $this->container['phone_mobile'] = $phone_mobile;

        return $this;
    }

    /**
     * Gets phone_home
     *
     * @return string|null
     */
    public function getPhoneHome()
    {
        return $this->container['phone_home'];
    }

    /**
     * Sets phone_home
     *
     * @param string|null $phone_home phone_home
     *
     * @return self
     */
    public function setPhoneHome($phone_home)
    {
        if (is_null($phone_home)) {
            throw new \InvalidArgumentException('non-nullable phone_home cannot be null');
        }
        $this->container['phone_home'] = $phone_home;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets zip
     *
     * @return string|null
     */
    public function getZip()
    {
        return $this->container['zip'];
    }

    /**
     * Sets zip
     *
     * @param string|null $zip zip
     *
     * @return self
     */
    public function setZip($zip)
    {
        if (is_null($zip)) {
            throw new \InvalidArgumentException('non-nullable zip cannot be null');
        }
        $this->container['zip'] = $zip;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets province
     *
     * @return string|null
     */
    public function getProvince()
    {
        return $this->container['province'];
    }

    /**
     * Sets province
     *
     * @param string|null $province province
     *
     * @return self
     */
    public function setProvince($province)
    {
        if (is_null($province)) {
            throw new \InvalidArgumentException('non-nullable province cannot be null');
        }
        $this->container['province'] = $province;

        return $this;
    }

    /**
     * Gets country_id
     *
     * @return int|null
     */
    public function getCountryId()
    {
        return $this->container['country_id'];
    }

    /**
     * Sets country_id
     *
     * @param int|null $country_id country_id
     *
     * @return self
     */
    public function setCountryId($country_id)
    {
        if (is_null($country_id)) {
            throw new \InvalidArgumentException('non-nullable country_id cannot be null');
        }
        $this->container['country_id'] = $country_id;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets membership_start
     *
     * @return \DateTime|null
     */
    public function getMembershipStart()
    {
        return $this->container['membership_start'];
    }

    /**
     * Sets membership_start
     *
     * @param \DateTime|null $membership_start membership_start
     *
     * @return self
     */
    public function setMembershipStart($membership_start)
    {
        if (is_null($membership_start)) {
            throw new \InvalidArgumentException('non-nullable membership_start cannot be null');
        }
        $this->container['membership_start'] = $membership_start;

        return $this;
    }

    /**
     * Gets membership_end
     *
     * @return \DateTime|null
     */
    public function getMembershipEnd()
    {
        return $this->container['membership_end'];
    }

    /**
     * Sets membership_end
     *
     * @param \DateTime|null $membership_end membership_end
     *
     * @return self
     */
    public function setMembershipEnd($membership_end)
    {
        if (is_null($membership_end)) {
            throw new \InvalidArgumentException('non-nullable membership_end cannot be null');
        }
        $this->container['membership_end'] = $membership_end;

        return $this;
    }

    /**
     * Gets current_member_status_name
     *
     * @return string|null
     */
    public function getCurrentMemberStatusName()
    {
        return $this->container['current_member_status_name'];
    }

    /**
     * Sets current_member_status_name
     *
     * @param string|null $current_member_status_name current_member_status_name
     *
     * @return self
     */
    public function setCurrentMemberStatusName($current_member_status_name)
    {
        if (is_null($current_member_status_name)) {
            throw new \InvalidArgumentException('non-nullable current_member_status_name cannot be null');
        }
        $this->container['current_member_status_name'] = $current_member_status_name;

        return $this;
    }

    /**
     * Gets current_member_status_id
     *
     * @return int|null
     */
    public function getCurrentMemberStatusId()
    {
        return $this->container['current_member_status_id'];
    }

    /**
     * Sets current_member_status_id
     *
     * @param int|null $current_member_status_id current_member_status_id
     *
     * @return self
     */
    public function setCurrentMemberStatusId($current_member_status_id)
    {
        if (is_null($current_member_status_id)) {
            throw new \InvalidArgumentException('non-nullable current_member_status_id cannot be null');
        }
        $this->container['current_member_status_id'] = $current_member_status_id;

        return $this;
    }

    /**
     * Gets manager_uri
     *
     * @return mixed|null
     */
    public function getManagerUri()
    {
        return $this->container['manager_uri'];
    }

    /**
     * Sets manager_uri
     *
     * @param mixed|null $manager_uri manager_uri
     *
     * @return self
     */
    public function setManagerUri($manager_uri)
    {
        if (is_null($manager_uri)) {
            array_push($this->openAPINullablesSetToNull, 'manager_uri');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('manager_uri', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['manager_uri'] = $manager_uri;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


