<?php
/**
 * EventParticipationWithRelations
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Congressus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@congressus.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Compucie\Congressus\Model;

use \ArrayAccess;
use \Compucie\Congressus\ObjectSerializer;

/**
 * EventParticipationWithRelations Class Doc Comment
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EventParticipationWithRelations implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EventParticipationWithRelations';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'event_id' => 'int',
        'member_id' => 'int',
        'sale_invoice_id' => 'int',
        'form_entry_id' => 'int',
        'rental_reservation_id' => 'int',
        'addressee' => 'string',
        'email' => 'string',
        'num_tickets_sold' => 'int',
        'uuid' => 'string',
        'status' => 'string',
        'access_key' => 'string',
        'remarks' => 'string',
        'participation_certificates_credits_override' => 'float',
        'participation_certificates_date_override' => '\DateTime',
        'event' => '\Compucie\Congressus\Model\Event',
        'member' => '\Compucie\Congressus\Model\MemberWithoutRelations',
        'tickets' => '\Compucie\Congressus\Model\EventParticipationTicket[]',
        'sale_invoice' => '\Compucie\Congressus\Model\SaleInvoice',
        'rental_reservation' => '\Compucie\Congressus\Model\RentalReservation'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'event_id' => null,
        'member_id' => null,
        'sale_invoice_id' => null,
        'form_entry_id' => null,
        'rental_reservation_id' => null,
        'addressee' => null,
        'email' => 'email',
        'num_tickets_sold' => null,
        'uuid' => 'uuid',
        'status' => null,
        'access_key' => 'uuid',
        'remarks' => null,
        'participation_certificates_credits_override' => null,
        'participation_certificates_date_override' => 'date',
        'event' => null,
        'member' => null,
        'tickets' => null,
        'sale_invoice' => null,
        'rental_reservation' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'event_id' => false,
        'member_id' => false,
        'sale_invoice_id' => false,
        'form_entry_id' => false,
        'rental_reservation_id' => false,
        'addressee' => false,
        'email' => false,
        'num_tickets_sold' => false,
        'uuid' => false,
        'status' => false,
        'access_key' => false,
        'remarks' => false,
        'participation_certificates_credits_override' => true,
        'participation_certificates_date_override' => true,
        'event' => false,
        'member' => false,
        'tickets' => false,
        'sale_invoice' => false,
        'rental_reservation' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'event_id' => 'event_id',
        'member_id' => 'member_id',
        'sale_invoice_id' => 'sale_invoice_id',
        'form_entry_id' => 'form_entry_id',
        'rental_reservation_id' => 'rental_reservation_id',
        'addressee' => 'addressee',
        'email' => 'email',
        'num_tickets_sold' => 'num_tickets_sold',
        'uuid' => 'uuid',
        'status' => 'status',
        'access_key' => 'access_key',
        'remarks' => 'remarks',
        'participation_certificates_credits_override' => 'participation_certificates_credits_override',
        'participation_certificates_date_override' => 'participation_certificates_date_override',
        'event' => 'event',
        'member' => 'member',
        'tickets' => 'tickets',
        'sale_invoice' => 'sale_invoice',
        'rental_reservation' => 'rental_reservation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'event_id' => 'setEventId',
        'member_id' => 'setMemberId',
        'sale_invoice_id' => 'setSaleInvoiceId',
        'form_entry_id' => 'setFormEntryId',
        'rental_reservation_id' => 'setRentalReservationId',
        'addressee' => 'setAddressee',
        'email' => 'setEmail',
        'num_tickets_sold' => 'setNumTicketsSold',
        'uuid' => 'setUuid',
        'status' => 'setStatus',
        'access_key' => 'setAccessKey',
        'remarks' => 'setRemarks',
        'participation_certificates_credits_override' => 'setParticipationCertificatesCreditsOverride',
        'participation_certificates_date_override' => 'setParticipationCertificatesDateOverride',
        'event' => 'setEvent',
        'member' => 'setMember',
        'tickets' => 'setTickets',
        'sale_invoice' => 'setSaleInvoice',
        'rental_reservation' => 'setRentalReservation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'event_id' => 'getEventId',
        'member_id' => 'getMemberId',
        'sale_invoice_id' => 'getSaleInvoiceId',
        'form_entry_id' => 'getFormEntryId',
        'rental_reservation_id' => 'getRentalReservationId',
        'addressee' => 'getAddressee',
        'email' => 'getEmail',
        'num_tickets_sold' => 'getNumTicketsSold',
        'uuid' => 'getUuid',
        'status' => 'getStatus',
        'access_key' => 'getAccessKey',
        'remarks' => 'getRemarks',
        'participation_certificates_credits_override' => 'getParticipationCertificatesCreditsOverride',
        'participation_certificates_date_override' => 'getParticipationCertificatesDateOverride',
        'event' => 'getEvent',
        'member' => 'getMember',
        'tickets' => 'getTickets',
        'sale_invoice' => 'getSaleInvoice',
        'rental_reservation' => 'getRentalReservation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('event_id', $data ?? [], null);
        $this->setIfExists('member_id', $data ?? [], null);
        $this->setIfExists('sale_invoice_id', $data ?? [], null);
        $this->setIfExists('form_entry_id', $data ?? [], null);
        $this->setIfExists('rental_reservation_id', $data ?? [], null);
        $this->setIfExists('addressee', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('num_tickets_sold', $data ?? [], null);
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('access_key', $data ?? [], null);
        $this->setIfExists('remarks', $data ?? [], null);
        $this->setIfExists('participation_certificates_credits_override', $data ?? [], null);
        $this->setIfExists('participation_certificates_date_override', $data ?? [], null);
        $this->setIfExists('event', $data ?? [], null);
        $this->setIfExists('member', $data ?? [], null);
        $this->setIfExists('tickets', $data ?? [], null);
        $this->setIfExists('sale_invoice', $data ?? [], null);
        $this->setIfExists('rental_reservation', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['event_id'] === null) {
            $invalidProperties[] = "'event_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets event_id
     *
     * @return int
     */
    public function getEventId()
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id
     *
     * @param int $event_id event_id
     *
     * @return self
     */
    public function setEventId($event_id)
    {
        if (is_null($event_id)) {
            throw new \InvalidArgumentException('non-nullable event_id cannot be null');
        }
        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets member_id
     *
     * @return int|null
     */
    public function getMemberId()
    {
        return $this->container['member_id'];
    }

    /**
     * Sets member_id
     *
     * @param int|null $member_id member_id
     *
     * @return self
     */
    public function setMemberId($member_id)
    {
        if (is_null($member_id)) {
            throw new \InvalidArgumentException('non-nullable member_id cannot be null');
        }
        $this->container['member_id'] = $member_id;

        return $this;
    }

    /**
     * Gets sale_invoice_id
     *
     * @return int|null
     */
    public function getSaleInvoiceId()
    {
        return $this->container['sale_invoice_id'];
    }

    /**
     * Sets sale_invoice_id
     *
     * @param int|null $sale_invoice_id sale_invoice_id
     *
     * @return self
     */
    public function setSaleInvoiceId($sale_invoice_id)
    {
        if (is_null($sale_invoice_id)) {
            throw new \InvalidArgumentException('non-nullable sale_invoice_id cannot be null');
        }
        $this->container['sale_invoice_id'] = $sale_invoice_id;

        return $this;
    }

    /**
     * Gets form_entry_id
     *
     * @return int|null
     */
    public function getFormEntryId()
    {
        return $this->container['form_entry_id'];
    }

    /**
     * Sets form_entry_id
     *
     * @param int|null $form_entry_id form_entry_id
     *
     * @return self
     */
    public function setFormEntryId($form_entry_id)
    {
        if (is_null($form_entry_id)) {
            throw new \InvalidArgumentException('non-nullable form_entry_id cannot be null');
        }
        $this->container['form_entry_id'] = $form_entry_id;

        return $this;
    }

    /**
     * Gets rental_reservation_id
     *
     * @return int|null
     */
    public function getRentalReservationId()
    {
        return $this->container['rental_reservation_id'];
    }

    /**
     * Sets rental_reservation_id
     *
     * @param int|null $rental_reservation_id rental_reservation_id
     *
     * @return self
     */
    public function setRentalReservationId($rental_reservation_id)
    {
        if (is_null($rental_reservation_id)) {
            throw new \InvalidArgumentException('non-nullable rental_reservation_id cannot be null');
        }
        $this->container['rental_reservation_id'] = $rental_reservation_id;

        return $this;
    }

    /**
     * Gets addressee
     *
     * @return string|null
     */
    public function getAddressee()
    {
        return $this->container['addressee'];
    }

    /**
     * Sets addressee
     *
     * @param string|null $addressee addressee
     *
     * @return self
     */
    public function setAddressee($addressee)
    {
        if (is_null($addressee)) {
            throw new \InvalidArgumentException('non-nullable addressee cannot be null');
        }
        $this->container['addressee'] = $addressee;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets num_tickets_sold
     *
     * @return int|null
     */
    public function getNumTicketsSold()
    {
        return $this->container['num_tickets_sold'];
    }

    /**
     * Sets num_tickets_sold
     *
     * @param int|null $num_tickets_sold Number of tickets sold for this participation
     *
     * @return self
     */
    public function setNumTicketsSold($num_tickets_sold)
    {
        if (is_null($num_tickets_sold)) {
            throw new \InvalidArgumentException('non-nullable num_tickets_sold cannot be null');
        }
        $this->container['num_tickets_sold'] = $num_tickets_sold;

        return $this;
    }

    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid uuid
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Status for this participation. You can update this status with action endpoints.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets access_key
     *
     * @return string|null
     */
    public function getAccessKey()
    {
        return $this->container['access_key'];
    }

    /**
     * Sets access_key
     *
     * @param string|null $access_key access_key
     *
     * @return self
     */
    public function setAccessKey($access_key)
    {
        if (is_null($access_key)) {
            throw new \InvalidArgumentException('non-nullable access_key cannot be null');
        }
        $this->container['access_key'] = $access_key;

        return $this;
    }

    /**
     * Gets remarks
     *
     * @return string|null
     */
    public function getRemarks()
    {
        return $this->container['remarks'];
    }

    /**
     * Sets remarks
     *
     * @param string|null $remarks Remarks added by the participant during order
     *
     * @return self
     */
    public function setRemarks($remarks)
    {
        if (is_null($remarks)) {
            throw new \InvalidArgumentException('non-nullable remarks cannot be null');
        }
        $this->container['remarks'] = $remarks;

        return $this;
    }

    /**
     * Gets participation_certificates_credits_override
     *
     * @return float|null
     */
    public function getParticipationCertificatesCreditsOverride()
    {
        return $this->container['participation_certificates_credits_override'];
    }

    /**
     * Sets participation_certificates_credits_override
     *
     * @param float|null $participation_certificates_credits_override Number of credits for the participation certificate. Set to 0 to disable certificate. Set to null to use the default value from the event.
     *
     * @return self
     */
    public function setParticipationCertificatesCreditsOverride($participation_certificates_credits_override)
    {
        if (is_null($participation_certificates_credits_override)) {
            array_push($this->openAPINullablesSetToNull, 'participation_certificates_credits_override');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('participation_certificates_credits_override', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['participation_certificates_credits_override'] = $participation_certificates_credits_override;

        return $this;
    }

    /**
     * Gets participation_certificates_date_override
     *
     * @return \DateTime|null
     */
    public function getParticipationCertificatesDateOverride()
    {
        return $this->container['participation_certificates_date_override'];
    }

    /**
     * Sets participation_certificates_date_override
     *
     * @param \DateTime|null $participation_certificates_date_override Date override for the participation certificate. Set to null to use the default value from the event.
     *
     * @return self
     */
    public function setParticipationCertificatesDateOverride($participation_certificates_date_override)
    {
        if (is_null($participation_certificates_date_override)) {
            array_push($this->openAPINullablesSetToNull, 'participation_certificates_date_override');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('participation_certificates_date_override', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['participation_certificates_date_override'] = $participation_certificates_date_override;

        return $this;
    }

    /**
     * Gets event
     *
     * @return \Compucie\Congressus\Model\Event|null
     */
    public function getEvent()
    {
        return $this->container['event'];
    }

    /**
     * Sets event
     *
     * @param \Compucie\Congressus\Model\Event|null $event event
     *
     * @return self
     */
    public function setEvent($event)
    {
        if (is_null($event)) {
            throw new \InvalidArgumentException('non-nullable event cannot be null');
        }
        $this->container['event'] = $event;

        return $this;
    }

    /**
     * Gets member
     *
     * @return \Compucie\Congressus\Model\MemberWithoutRelations|null
     */
    public function getMember()
    {
        return $this->container['member'];
    }

    /**
     * Sets member
     *
     * @param \Compucie\Congressus\Model\MemberWithoutRelations|null $member member
     *
     * @return self
     */
    public function setMember($member)
    {
        if (is_null($member)) {
            throw new \InvalidArgumentException('non-nullable member cannot be null');
        }
        $this->container['member'] = $member;

        return $this;
    }

    /**
     * Gets tickets
     *
     * @return \Compucie\Congressus\Model\EventParticipationTicket[]|null
     */
    public function getTickets()
    {
        return $this->container['tickets'];
    }

    /**
     * Sets tickets
     *
     * @param \Compucie\Congressus\Model\EventParticipationTicket[]|null $tickets tickets
     *
     * @return self
     */
    public function setTickets($tickets)
    {
        if (is_null($tickets)) {
            throw new \InvalidArgumentException('non-nullable tickets cannot be null');
        }
        $this->container['tickets'] = $tickets;

        return $this;
    }

    /**
     * Gets sale_invoice
     *
     * @return \Compucie\Congressus\Model\SaleInvoice|null
     */
    public function getSaleInvoice()
    {
        return $this->container['sale_invoice'];
    }

    /**
     * Sets sale_invoice
     *
     * @param \Compucie\Congressus\Model\SaleInvoice|null $sale_invoice sale_invoice
     *
     * @return self
     */
    public function setSaleInvoice($sale_invoice)
    {
        if (is_null($sale_invoice)) {
            throw new \InvalidArgumentException('non-nullable sale_invoice cannot be null');
        }
        $this->container['sale_invoice'] = $sale_invoice;

        return $this;
    }

    /**
     * Gets rental_reservation
     *
     * @return \Compucie\Congressus\Model\RentalReservation|null
     */
    public function getRentalReservation()
    {
        return $this->container['rental_reservation'];
    }

    /**
     * Sets rental_reservation
     *
     * @param \Compucie\Congressus\Model\RentalReservation|null $rental_reservation rental_reservation
     *
     * @return self
     */
    public function setRentalReservation($rental_reservation)
    {
        if (is_null($rental_reservation)) {
            throw new \InvalidArgumentException('non-nullable rental_reservation cannot be null');
        }
        $this->container['rental_reservation'] = $rental_reservation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


