<?php
/**
 * LogEntry
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Congressus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@congressus.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Compucie\Congressus\Model;

use \ArrayAccess;
use \Compucie\Congressus\ObjectSerializer;

/**
 * LogEntry Class Doc Comment
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LogEntry implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LogEntry';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'type' => 'string',
        'text' => 'string',
        'subject_type' => 'string',
        'subject_id' => 'int',
        'author_id' => 'int',
        'created' => '\DateTime',
        'modified' => '\DateTime',
        'author' => '\Compucie\Congressus\Model\LogEntryUser',
        'subject' => '\Compucie\Congressus\Model\LogEntrySubject',
        'assignee_type' => 'string',
        'assignee_id' => 'int',
        'assignee' => '\Compucie\Congressus\Model\LogEntryUser',
        'is_completed' => 'bool',
        'completed' => '\DateTime',
        'completed_by_id' => 'int',
        'completed_by' => '\Compucie\Congressus\Model\LogEntryUser',
        'action' => 'object',
        'changes' => 'object',
        'changes_pretty' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'type' => null,
        'text' => null,
        'subject_type' => null,
        'subject_id' => null,
        'author_id' => null,
        'created' => 'date-time',
        'modified' => 'date-time',
        'author' => null,
        'subject' => null,
        'assignee_type' => null,
        'assignee_id' => null,
        'assignee' => null,
        'is_completed' => null,
        'completed' => 'date-time',
        'completed_by_id' => null,
        'completed_by' => null,
        'action' => null,
        'changes' => null,
        'changes_pretty' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'type' => false,
        'text' => true,
        'subject_type' => false,
        'subject_id' => false,
        'author_id' => true,
        'created' => true,
        'modified' => true,
        'author' => false,
        'subject' => false,
        'assignee_type' => true,
        'assignee_id' => true,
        'assignee' => false,
        'is_completed' => false,
        'completed' => true,
        'completed_by_id' => true,
        'completed_by' => false,
        'action' => false,
        'changes' => false,
        'changes_pretty' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'type' => 'type',
        'text' => 'text',
        'subject_type' => 'subject_type',
        'subject_id' => 'subject_id',
        'author_id' => 'author_id',
        'created' => 'created',
        'modified' => 'modified',
        'author' => 'author',
        'subject' => 'subject',
        'assignee_type' => 'assignee_type',
        'assignee_id' => 'assignee_id',
        'assignee' => 'assignee',
        'is_completed' => 'is_completed',
        'completed' => 'completed',
        'completed_by_id' => 'completed_by_id',
        'completed_by' => 'completed_by',
        'action' => 'action',
        'changes' => 'changes',
        'changes_pretty' => 'changes_pretty'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'type' => 'setType',
        'text' => 'setText',
        'subject_type' => 'setSubjectType',
        'subject_id' => 'setSubjectId',
        'author_id' => 'setAuthorId',
        'created' => 'setCreated',
        'modified' => 'setModified',
        'author' => 'setAuthor',
        'subject' => 'setSubject',
        'assignee_type' => 'setAssigneeType',
        'assignee_id' => 'setAssigneeId',
        'assignee' => 'setAssignee',
        'is_completed' => 'setIsCompleted',
        'completed' => 'setCompleted',
        'completed_by_id' => 'setCompletedById',
        'completed_by' => 'setCompletedBy',
        'action' => 'setAction',
        'changes' => 'setChanges',
        'changes_pretty' => 'setChangesPretty'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'type' => 'getType',
        'text' => 'getText',
        'subject_type' => 'getSubjectType',
        'subject_id' => 'getSubjectId',
        'author_id' => 'getAuthorId',
        'created' => 'getCreated',
        'modified' => 'getModified',
        'author' => 'getAuthor',
        'subject' => 'getSubject',
        'assignee_type' => 'getAssigneeType',
        'assignee_id' => 'getAssigneeId',
        'assignee' => 'getAssignee',
        'is_completed' => 'getIsCompleted',
        'completed' => 'getCompleted',
        'completed_by_id' => 'getCompletedById',
        'completed_by' => 'getCompletedBy',
        'action' => 'getAction',
        'changes' => 'getChanges',
        'changes_pretty' => 'getChangesPretty'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('subject_type', $data ?? [], null);
        $this->setIfExists('subject_id', $data ?? [], null);
        $this->setIfExists('author_id', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('modified', $data ?? [], null);
        $this->setIfExists('author', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('assignee_type', $data ?? [], null);
        $this->setIfExists('assignee_id', $data ?? [], null);
        $this->setIfExists('assignee', $data ?? [], null);
        $this->setIfExists('is_completed', $data ?? [], null);
        $this->setIfExists('completed', $data ?? [], null);
        $this->setIfExists('completed_by_id', $data ?? [], null);
        $this->setIfExists('completed_by', $data ?? [], null);
        $this->setIfExists('action', $data ?? [], null);
        $this->setIfExists('changes', $data ?? [], null);
        $this->setIfExists('changes_pretty', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ((mb_strlen($this->container['type']) > 255)) {
            $invalidProperties[] = "invalid value for 'type', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['subject_type'] === null) {
            $invalidProperties[] = "'subject_type' can't be null";
        }
        if ((mb_strlen($this->container['subject_type']) > 255)) {
            $invalidProperties[] = "invalid value for 'subject_type', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['subject_id'] === null) {
            $invalidProperties[] = "'subject_id' can't be null";
        }
        if (!is_null($this->container['assignee_type']) && (mb_strlen($this->container['assignee_type']) > 255)) {
            $invalidProperties[] = "invalid value for 'assignee_type', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['changes'] === null) {
            $invalidProperties[] = "'changes' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        if ((mb_strlen($type) > 255)) {
            throw new \InvalidArgumentException('invalid length for $type when calling LogEntry., must be smaller than or equal to 255.');
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text text
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            array_push($this->openAPINullablesSetToNull, 'text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets subject_type
     *
     * @return string
     */
    public function getSubjectType()
    {
        return $this->container['subject_type'];
    }

    /**
     * Sets subject_type
     *
     * @param string $subject_type subject_type
     *
     * @return self
     */
    public function setSubjectType($subject_type)
    {
        if (is_null($subject_type)) {
            throw new \InvalidArgumentException('non-nullable subject_type cannot be null');
        }
        if ((mb_strlen($subject_type) > 255)) {
            throw new \InvalidArgumentException('invalid length for $subject_type when calling LogEntry., must be smaller than or equal to 255.');
        }

        $this->container['subject_type'] = $subject_type;

        return $this;
    }

    /**
     * Gets subject_id
     *
     * @return int
     */
    public function getSubjectId()
    {
        return $this->container['subject_id'];
    }

    /**
     * Sets subject_id
     *
     * @param int $subject_id subject_id
     *
     * @return self
     */
    public function setSubjectId($subject_id)
    {
        if (is_null($subject_id)) {
            throw new \InvalidArgumentException('non-nullable subject_id cannot be null');
        }
        $this->container['subject_id'] = $subject_id;

        return $this;
    }

    /**
     * Gets author_id
     *
     * @return int|null
     */
    public function getAuthorId()
    {
        return $this->container['author_id'];
    }

    /**
     * Sets author_id
     *
     * @param int|null $author_id author_id
     *
     * @return self
     */
    public function setAuthorId($author_id)
    {
        if (is_null($author_id)) {
            array_push($this->openAPINullablesSetToNull, 'author_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('author_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['author_id'] = $author_id;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime|null
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime|null $created created
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            array_push($this->openAPINullablesSetToNull, 'created');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets modified
     *
     * @return \DateTime|null
     */
    public function getModified()
    {
        return $this->container['modified'];
    }

    /**
     * Sets modified
     *
     * @param \DateTime|null $modified modified
     *
     * @return self
     */
    public function setModified($modified)
    {
        if (is_null($modified)) {
            array_push($this->openAPINullablesSetToNull, 'modified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('modified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['modified'] = $modified;

        return $this;
    }

    /**
     * Gets author
     *
     * @return \Compucie\Congressus\Model\LogEntryUser|null
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param \Compucie\Congressus\Model\LogEntryUser|null $author author
     *
     * @return self
     */
    public function setAuthor($author)
    {
        if (is_null($author)) {
            throw new \InvalidArgumentException('non-nullable author cannot be null');
        }
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return \Compucie\Congressus\Model\LogEntrySubject|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param \Compucie\Congressus\Model\LogEntrySubject|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets assignee_type
     *
     * @return string|null
     */
    public function getAssigneeType()
    {
        return $this->container['assignee_type'];
    }

    /**
     * Sets assignee_type
     *
     * @param string|null $assignee_type assignee_type
     *
     * @return self
     */
    public function setAssigneeType($assignee_type)
    {
        if (is_null($assignee_type)) {
            array_push($this->openAPINullablesSetToNull, 'assignee_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('assignee_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($assignee_type) && (mb_strlen($assignee_type) > 255)) {
            throw new \InvalidArgumentException('invalid length for $assignee_type when calling LogEntry., must be smaller than or equal to 255.');
        }

        $this->container['assignee_type'] = $assignee_type;

        return $this;
    }

    /**
     * Gets assignee_id
     *
     * @return int|null
     */
    public function getAssigneeId()
    {
        return $this->container['assignee_id'];
    }

    /**
     * Sets assignee_id
     *
     * @param int|null $assignee_id assignee_id
     *
     * @return self
     */
    public function setAssigneeId($assignee_id)
    {
        if (is_null($assignee_id)) {
            array_push($this->openAPINullablesSetToNull, 'assignee_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('assignee_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['assignee_id'] = $assignee_id;

        return $this;
    }

    /**
     * Gets assignee
     *
     * @return \Compucie\Congressus\Model\LogEntryUser|null
     */
    public function getAssignee()
    {
        return $this->container['assignee'];
    }

    /**
     * Sets assignee
     *
     * @param \Compucie\Congressus\Model\LogEntryUser|null $assignee assignee
     *
     * @return self
     */
    public function setAssignee($assignee)
    {
        if (is_null($assignee)) {
            throw new \InvalidArgumentException('non-nullable assignee cannot be null');
        }
        $this->container['assignee'] = $assignee;

        return $this;
    }

    /**
     * Gets is_completed
     *
     * @return bool|null
     */
    public function getIsCompleted()
    {
        return $this->container['is_completed'];
    }

    /**
     * Sets is_completed
     *
     * @param bool|null $is_completed is_completed
     *
     * @return self
     */
    public function setIsCompleted($is_completed)
    {
        if (is_null($is_completed)) {
            throw new \InvalidArgumentException('non-nullable is_completed cannot be null');
        }
        $this->container['is_completed'] = $is_completed;

        return $this;
    }

    /**
     * Gets completed
     *
     * @return \DateTime|null
     */
    public function getCompleted()
    {
        return $this->container['completed'];
    }

    /**
     * Sets completed
     *
     * @param \DateTime|null $completed completed
     *
     * @return self
     */
    public function setCompleted($completed)
    {
        if (is_null($completed)) {
            array_push($this->openAPINullablesSetToNull, 'completed');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('completed', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['completed'] = $completed;

        return $this;
    }

    /**
     * Gets completed_by_id
     *
     * @return int|null
     */
    public function getCompletedById()
    {
        return $this->container['completed_by_id'];
    }

    /**
     * Sets completed_by_id
     *
     * @param int|null $completed_by_id completed_by_id
     *
     * @return self
     */
    public function setCompletedById($completed_by_id)
    {
        if (is_null($completed_by_id)) {
            array_push($this->openAPINullablesSetToNull, 'completed_by_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('completed_by_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['completed_by_id'] = $completed_by_id;

        return $this;
    }

    /**
     * Gets completed_by
     *
     * @return \Compucie\Congressus\Model\LogEntryUser|null
     */
    public function getCompletedBy()
    {
        return $this->container['completed_by'];
    }

    /**
     * Sets completed_by
     *
     * @param \Compucie\Congressus\Model\LogEntryUser|null $completed_by completed_by
     *
     * @return self
     */
    public function setCompletedBy($completed_by)
    {
        if (is_null($completed_by)) {
            throw new \InvalidArgumentException('non-nullable completed_by cannot be null');
        }
        $this->container['completed_by'] = $completed_by;

        return $this;
    }

    /**
     * Gets action
     *
     * @return object|null
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param object|null $action action
     *
     * @return self
     */
    public function setAction($action)
    {
        if (is_null($action)) {
            throw new \InvalidArgumentException('non-nullable action cannot be null');
        }
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets changes
     *
     * @return object
     */
    public function getChanges()
    {
        return $this->container['changes'];
    }

    /**
     * Sets changes
     *
     * @param object $changes changes
     *
     * @return self
     */
    public function setChanges($changes)
    {
        if (is_null($changes)) {
            throw new \InvalidArgumentException('non-nullable changes cannot be null');
        }
        $this->container['changes'] = $changes;

        return $this;
    }

    /**
     * Gets changes_pretty
     *
     * @return object|null
     */
    public function getChangesPretty()
    {
        return $this->container['changes_pretty'];
    }

    /**
     * Sets changes_pretty
     *
     * @param object|null $changes_pretty changes_pretty
     *
     * @return self
     */
    public function setChangesPretty($changes_pretty)
    {
        if (is_null($changes_pretty)) {
            throw new \InvalidArgumentException('non-nullable changes_pretty cannot be null');
        }
        $this->container['changes_pretty'] = $changes_pretty;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


