<?php
/**
 * Website
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Congressus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@congressus.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Compucie\Congressus\Model;

use \ArrayAccess;
use \Compucie\Congressus\ObjectSerializer;

/**
 * Website Class Doc Comment
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Website implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Website';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'url' => 'string',
        'active' => 'bool',
        'locale' => '\Compucie\Congressus\Model\Locale',
        'description' => 'string',
        'ga_tracking_id' => 'string',
        'custom_domain' => 'string',
        'domain_path' => 'string',
        'font_base' => 'string',
        'font_headings' => 'string',
        'color_primary' => 'string',
        'color_secondary' => 'string',
        'color_background' => 'string',
        'template_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'url' => 'url',
        'active' => null,
        'locale' => null,
        'description' => null,
        'ga_tracking_id' => null,
        'custom_domain' => null,
        'domain_path' => null,
        'font_base' => null,
        'font_headings' => null,
        'color_primary' => null,
        'color_secondary' => null,
        'color_background' => null,
        'template_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'url' => false,
        'active' => true,
        'locale' => false,
        'description' => true,
        'ga_tracking_id' => true,
        'custom_domain' => true,
        'domain_path' => true,
        'font_base' => true,
        'font_headings' => true,
        'color_primary' => true,
        'color_secondary' => true,
        'color_background' => true,
        'template_id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'url' => 'url',
        'active' => 'active',
        'locale' => 'locale',
        'description' => 'description',
        'ga_tracking_id' => 'ga_tracking_id',
        'custom_domain' => 'custom_domain',
        'domain_path' => 'domain_path',
        'font_base' => 'font_base',
        'font_headings' => 'font_headings',
        'color_primary' => 'color_primary',
        'color_secondary' => 'color_secondary',
        'color_background' => 'color_background',
        'template_id' => 'template_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'url' => 'setUrl',
        'active' => 'setActive',
        'locale' => 'setLocale',
        'description' => 'setDescription',
        'ga_tracking_id' => 'setGaTrackingId',
        'custom_domain' => 'setCustomDomain',
        'domain_path' => 'setDomainPath',
        'font_base' => 'setFontBase',
        'font_headings' => 'setFontHeadings',
        'color_primary' => 'setColorPrimary',
        'color_secondary' => 'setColorSecondary',
        'color_background' => 'setColorBackground',
        'template_id' => 'setTemplateId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'url' => 'getUrl',
        'active' => 'getActive',
        'locale' => 'getLocale',
        'description' => 'getDescription',
        'ga_tracking_id' => 'getGaTrackingId',
        'custom_domain' => 'getCustomDomain',
        'domain_path' => 'getDomainPath',
        'font_base' => 'getFontBase',
        'font_headings' => 'getFontHeadings',
        'color_primary' => 'getColorPrimary',
        'color_secondary' => 'getColorSecondary',
        'color_background' => 'getColorBackground',
        'template_id' => 'getTemplateId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('active', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('ga_tracking_id', $data ?? [], null);
        $this->setIfExists('custom_domain', $data ?? [], null);
        $this->setIfExists('domain_path', $data ?? [], null);
        $this->setIfExists('font_base', $data ?? [], null);
        $this->setIfExists('font_headings', $data ?? [], null);
        $this->setIfExists('color_primary', $data ?? [], null);
        $this->setIfExists('color_secondary', $data ?? [], null);
        $this->setIfExists('color_background', $data ?? [], null);
        $this->setIfExists('template_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['ga_tracking_id']) && (mb_strlen($this->container['ga_tracking_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'ga_tracking_id', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['custom_domain']) && (mb_strlen($this->container['custom_domain']) > 255)) {
            $invalidProperties[] = "invalid value for 'custom_domain', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['domain_path']) && (mb_strlen($this->container['domain_path']) > 128)) {
            $invalidProperties[] = "invalid value for 'domain_path', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['font_base']) && (mb_strlen($this->container['font_base']) > 255)) {
            $invalidProperties[] = "invalid value for 'font_base', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['font_headings']) && (mb_strlen($this->container['font_headings']) > 255)) {
            $invalidProperties[] = "invalid value for 'font_headings', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['color_primary']) && (mb_strlen($this->container['color_primary']) > 16)) {
            $invalidProperties[] = "invalid value for 'color_primary', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['color_secondary']) && (mb_strlen($this->container['color_secondary']) > 16)) {
            $invalidProperties[] = "invalid value for 'color_secondary', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['color_background']) && (mb_strlen($this->container['color_background']) > 16)) {
            $invalidProperties[] = "invalid value for 'color_background', the character length must be smaller than or equal to 16.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Website., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool|null $active active
     *
     * @return self
     */
    public function setActive($active)
    {
        if (is_null($active)) {
            array_push($this->openAPINullablesSetToNull, 'active');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('active', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return \Compucie\Congressus\Model\Locale|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param \Compucie\Congressus\Model\Locale|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets ga_tracking_id
     *
     * @return string|null
     */
    public function getGaTrackingId()
    {
        return $this->container['ga_tracking_id'];
    }

    /**
     * Sets ga_tracking_id
     *
     * @param string|null $ga_tracking_id ga_tracking_id
     *
     * @return self
     */
    public function setGaTrackingId($ga_tracking_id)
    {
        if (is_null($ga_tracking_id)) {
            array_push($this->openAPINullablesSetToNull, 'ga_tracking_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ga_tracking_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($ga_tracking_id) && (mb_strlen($ga_tracking_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $ga_tracking_id when calling Website., must be smaller than or equal to 64.');
        }

        $this->container['ga_tracking_id'] = $ga_tracking_id;

        return $this;
    }

    /**
     * Gets custom_domain
     *
     * @return string|null
     */
    public function getCustomDomain()
    {
        return $this->container['custom_domain'];
    }

    /**
     * Sets custom_domain
     *
     * @param string|null $custom_domain custom_domain
     *
     * @return self
     */
    public function setCustomDomain($custom_domain)
    {
        if (is_null($custom_domain)) {
            array_push($this->openAPINullablesSetToNull, 'custom_domain');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_domain', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($custom_domain) && (mb_strlen($custom_domain) > 255)) {
            throw new \InvalidArgumentException('invalid length for $custom_domain when calling Website., must be smaller than or equal to 255.');
        }

        $this->container['custom_domain'] = $custom_domain;

        return $this;
    }

    /**
     * Gets domain_path
     *
     * @return string|null
     */
    public function getDomainPath()
    {
        return $this->container['domain_path'];
    }

    /**
     * Sets domain_path
     *
     * @param string|null $domain_path domain_path
     *
     * @return self
     */
    public function setDomainPath($domain_path)
    {
        if (is_null($domain_path)) {
            array_push($this->openAPINullablesSetToNull, 'domain_path');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domain_path', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($domain_path) && (mb_strlen($domain_path) > 128)) {
            throw new \InvalidArgumentException('invalid length for $domain_path when calling Website., must be smaller than or equal to 128.');
        }

        $this->container['domain_path'] = $domain_path;

        return $this;
    }

    /**
     * Gets font_base
     *
     * @return string|null
     */
    public function getFontBase()
    {
        return $this->container['font_base'];
    }

    /**
     * Sets font_base
     *
     * @param string|null $font_base font_base
     *
     * @return self
     */
    public function setFontBase($font_base)
    {
        if (is_null($font_base)) {
            array_push($this->openAPINullablesSetToNull, 'font_base');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('font_base', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($font_base) && (mb_strlen($font_base) > 255)) {
            throw new \InvalidArgumentException('invalid length for $font_base when calling Website., must be smaller than or equal to 255.');
        }

        $this->container['font_base'] = $font_base;

        return $this;
    }

    /**
     * Gets font_headings
     *
     * @return string|null
     */
    public function getFontHeadings()
    {
        return $this->container['font_headings'];
    }

    /**
     * Sets font_headings
     *
     * @param string|null $font_headings font_headings
     *
     * @return self
     */
    public function setFontHeadings($font_headings)
    {
        if (is_null($font_headings)) {
            array_push($this->openAPINullablesSetToNull, 'font_headings');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('font_headings', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($font_headings) && (mb_strlen($font_headings) > 255)) {
            throw new \InvalidArgumentException('invalid length for $font_headings when calling Website., must be smaller than or equal to 255.');
        }

        $this->container['font_headings'] = $font_headings;

        return $this;
    }

    /**
     * Gets color_primary
     *
     * @return string|null
     */
    public function getColorPrimary()
    {
        return $this->container['color_primary'];
    }

    /**
     * Sets color_primary
     *
     * @param string|null $color_primary color_primary
     *
     * @return self
     */
    public function setColorPrimary($color_primary)
    {
        if (is_null($color_primary)) {
            array_push($this->openAPINullablesSetToNull, 'color_primary');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('color_primary', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($color_primary) && (mb_strlen($color_primary) > 16)) {
            throw new \InvalidArgumentException('invalid length for $color_primary when calling Website., must be smaller than or equal to 16.');
        }

        $this->container['color_primary'] = $color_primary;

        return $this;
    }

    /**
     * Gets color_secondary
     *
     * @return string|null
     */
    public function getColorSecondary()
    {
        return $this->container['color_secondary'];
    }

    /**
     * Sets color_secondary
     *
     * @param string|null $color_secondary color_secondary
     *
     * @return self
     */
    public function setColorSecondary($color_secondary)
    {
        if (is_null($color_secondary)) {
            array_push($this->openAPINullablesSetToNull, 'color_secondary');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('color_secondary', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($color_secondary) && (mb_strlen($color_secondary) > 16)) {
            throw new \InvalidArgumentException('invalid length for $color_secondary when calling Website., must be smaller than or equal to 16.');
        }

        $this->container['color_secondary'] = $color_secondary;

        return $this;
    }

    /**
     * Gets color_background
     *
     * @return string|null
     */
    public function getColorBackground()
    {
        return $this->container['color_background'];
    }

    /**
     * Sets color_background
     *
     * @param string|null $color_background color_background
     *
     * @return self
     */
    public function setColorBackground($color_background)
    {
        if (is_null($color_background)) {
            array_push($this->openAPINullablesSetToNull, 'color_background');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('color_background', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($color_background) && (mb_strlen($color_background) > 16)) {
            throw new \InvalidArgumentException('invalid length for $color_background when calling Website., must be smaller than or equal to 16.');
        }

        $this->container['color_background'] = $color_background;

        return $this;
    }

    /**
     * Gets template_id
     *
     * @return int|null
     */
    public function getTemplateId()
    {
        return $this->container['template_id'];
    }

    /**
     * Sets template_id
     *
     * @param int|null $template_id template_id
     *
     * @return self
     */
    public function setTemplateId($template_id)
    {
        if (is_null($template_id)) {
            array_push($this->openAPINullablesSetToNull, 'template_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('template_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['template_id'] = $template_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


