<?php

use NathanEmanuel\Congressus\Rest\RestClient;

require_once __DIR__ . "/../../vendor/autoload.php";

$client = new RestClient(getenv('congressus'));
// $client->listBackgroundProcesses(1);
// $client->listBankMutations(1);
$client->listBlogAuthors(1);
$client->listBlogCategories(1);
$client->listBlogIssues(1);
$client->listBlogs(1);
$client->listCareerPartnerCategories(1);
$client->listCareerPartners(1);
$client->listCountries(1);
$client->listCustomFields(1);
$client->listEventCategories(1);
$client->listEventParticipations(1, 1);
$client->listEvents(1);
$client->listFilters(1);
$client->listFormEntries(1, 1);
$client->listFormFields(1, 1);
$client->listForms(1);
$client->listGalleryAlbums(1);
$client->listGalleryPhotos(1, 1);
$client->listGroupFolders(1);
$client->listGroupFoldersRecursive(1);
$client->listGroupMemberships(1);
$client->listGroups(1);
$client->listMemberLogEntries(1, 1);
$client->listMembers(1);
$client->listMembershipStatuses(1, 1);
$client->listMemberStatuses(1);
$client->listNews(1);
$client->listNewsLogEntries(1, 1);
// $client->listNotifications(1);
// $client->listOrganisationCategories(1);
// $client->listOrganisationMemberships(1);
// $client->listOrganisations(1);
$client->listProductFolders(1);
$client->listProductFoldersRecursive(1);
$client->listProductLogEntries(1, 1);
$client->listProducts(1);
$client->listSaleInvoiceItems(1, 1);
$client->listSaleInvoiceLogEntries(1, 1);
$client->listSaleInvoices(1);
$client->listSaleInvoiceWorkflows(1);
$client->listSavedReplies(1);
$client->listStorageFolders(1);
$client->listStorageFoldersRecursive(1);
$client->listStorageObjects(1);
$client->listTasks(1);
$client->listTicketTypes(1, 1);
$client->listWebhookCalls(1, 1);
$client->listWebhooks(1);
$client->listWebpages(1);
$client->listWebsites(1);
$client->listWebsiteWebpages(1, 1);
