<?php
/**
 * EventTicketType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Congressus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@congressus.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Compucie\Congressus\models;

use \ArrayAccess;
use \Compucie\Congressus\ObjectSerializer;

/**
 * EventTicketType Class Doc Comment
 *
 * @category Class
 * @package  Compucie\Congressus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EventTicketType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EventTicketType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'availability_status' => 'string',
        'available_from' => '\DateTime',
        'available_to' => '\DateTime',
        'cancel_to' => '\DateTime',
        'confirmation_email_text' => 'string',
        'confirmation_email_text_enabled' => 'bool',
        'description' => 'string',
        'event_id' => 'int',
        'filter_id' => 'int',
        'id' => 'int',
        'modified' => '\DateTime',
        'name' => 'string',
        'num_tickets' => 'int',
        'num_tickets_available' => 'mixed',
        'num_tickets_max' => 'int',
        'num_tickets_max_per' => 'string',
        'num_tickets_sold' => 'int',
        'price' => 'float',
        'pricing_enabled' => 'bool',
        'vat_category' => '\Compucie\Congressus\models\VatCategory',
        'vat_category_id' => 'int',
        'visibility_level' => 'string',
        'waiting_list_enabled' => 'bool',
        'participation_certificate_credits' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'availability_status' => null,
        'available_from' => 'date-time',
        'available_to' => 'date-time',
        'cancel_to' => 'date-time',
        'confirmation_email_text' => null,
        'confirmation_email_text_enabled' => null,
        'description' => null,
        'event_id' => null,
        'filter_id' => null,
        'id' => null,
        'modified' => 'date-time',
        'name' => null,
        'num_tickets' => null,
        'num_tickets_available' => null,
        'num_tickets_max' => null,
        'num_tickets_max_per' => null,
        'num_tickets_sold' => null,
        'price' => null,
        'pricing_enabled' => null,
        'vat_category' => null,
        'vat_category_id' => null,
        'visibility_level' => null,
        'waiting_list_enabled' => null,
        'participation_certificate_credits' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'availability_status' => false,
        'available_from' => true,
        'available_to' => true,
        'cancel_to' => true,
        'confirmation_email_text' => true,
        'confirmation_email_text_enabled' => false,
        'description' => true,
        'event_id' => true,
        'filter_id' => true,
        'id' => false,
        'modified' => true,
        'name' => false,
        'num_tickets' => false,
        'num_tickets_available' => true,
        'num_tickets_max' => true,
        'num_tickets_max_per' => true,
        'num_tickets_sold' => false,
        'price' => true,
        'pricing_enabled' => true,
        'vat_category' => false,
        'vat_category_id' => true,
        'visibility_level' => false,
        'waiting_list_enabled' => true,
        'participation_certificate_credits' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'availability_status' => 'availability_status',
        'available_from' => 'available_from',
        'available_to' => 'available_to',
        'cancel_to' => 'cancel_to',
        'confirmation_email_text' => 'confirmation_email_text',
        'confirmation_email_text_enabled' => 'confirmation_email_text_enabled',
        'description' => 'description',
        'event_id' => 'event_id',
        'filter_id' => 'filter_id',
        'id' => 'id',
        'modified' => 'modified',
        'name' => 'name',
        'num_tickets' => 'num_tickets',
        'num_tickets_available' => 'num_tickets_available',
        'num_tickets_max' => 'num_tickets_max',
        'num_tickets_max_per' => 'num_tickets_max_per',
        'num_tickets_sold' => 'num_tickets_sold',
        'price' => 'price',
        'pricing_enabled' => 'pricing_enabled',
        'vat_category' => 'vat_category',
        'vat_category_id' => 'vat_category_id',
        'visibility_level' => 'visibility_level',
        'waiting_list_enabled' => 'waiting_list_enabled',
        'participation_certificate_credits' => 'participation_certificate_credits'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'availability_status' => 'setAvailabilityStatus',
        'available_from' => 'setAvailableFrom',
        'available_to' => 'setAvailableTo',
        'cancel_to' => 'setCancelTo',
        'confirmation_email_text' => 'setConfirmationEmailText',
        'confirmation_email_text_enabled' => 'setConfirmationEmailTextEnabled',
        'description' => 'setDescription',
        'event_id' => 'setEventId',
        'filter_id' => 'setFilterId',
        'id' => 'setId',
        'modified' => 'setModified',
        'name' => 'setName',
        'num_tickets' => 'setNumTickets',
        'num_tickets_available' => 'setNumTicketsAvailable',
        'num_tickets_max' => 'setNumTicketsMax',
        'num_tickets_max_per' => 'setNumTicketsMaxPer',
        'num_tickets_sold' => 'setNumTicketsSold',
        'price' => 'setPrice',
        'pricing_enabled' => 'setPricingEnabled',
        'vat_category' => 'setVatCategory',
        'vat_category_id' => 'setVatCategoryId',
        'visibility_level' => 'setVisibilityLevel',
        'waiting_list_enabled' => 'setWaitingListEnabled',
        'participation_certificate_credits' => 'setParticipationCertificateCredits'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'availability_status' => 'getAvailabilityStatus',
        'available_from' => 'getAvailableFrom',
        'available_to' => 'getAvailableTo',
        'cancel_to' => 'getCancelTo',
        'confirmation_email_text' => 'getConfirmationEmailText',
        'confirmation_email_text_enabled' => 'getConfirmationEmailTextEnabled',
        'description' => 'getDescription',
        'event_id' => 'getEventId',
        'filter_id' => 'getFilterId',
        'id' => 'getId',
        'modified' => 'getModified',
        'name' => 'getName',
        'num_tickets' => 'getNumTickets',
        'num_tickets_available' => 'getNumTicketsAvailable',
        'num_tickets_max' => 'getNumTicketsMax',
        'num_tickets_max_per' => 'getNumTicketsMaxPer',
        'num_tickets_sold' => 'getNumTicketsSold',
        'price' => 'getPrice',
        'pricing_enabled' => 'getPricingEnabled',
        'vat_category' => 'getVatCategory',
        'vat_category_id' => 'getVatCategoryId',
        'visibility_level' => 'getVisibilityLevel',
        'waiting_list_enabled' => 'getWaitingListEnabled',
        'participation_certificate_credits' => 'getParticipationCertificateCredits'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AVAILABILITY_STATUS_AVAILABLE = 'available';
    public const AVAILABILITY_STATUS_LIMITED = 'limited';
    public const AVAILABILITY_STATUS_WAITING_LIST = 'waiting list';
    public const AVAILABILITY_STATUS_SOLD_OUT = 'sold out';
    public const AVAILABILITY_STATUS_AVAILABLE_SOON = 'available soon';
    public const AVAILABILITY_STATUS_UNAVAILABLE = 'unavailable';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAvailabilityStatusAllowableValues()
    {
        return [
            self::AVAILABILITY_STATUS_AVAILABLE,
            self::AVAILABILITY_STATUS_LIMITED,
            self::AVAILABILITY_STATUS_WAITING_LIST,
            self::AVAILABILITY_STATUS_SOLD_OUT,
            self::AVAILABILITY_STATUS_AVAILABLE_SOON,
            self::AVAILABILITY_STATUS_UNAVAILABLE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('availability_status', $data ?? [], null);
        $this->setIfExists('available_from', $data ?? [], null);
        $this->setIfExists('available_to', $data ?? [], null);
        $this->setIfExists('cancel_to', $data ?? [], null);
        $this->setIfExists('confirmation_email_text', $data ?? [], null);
        $this->setIfExists('confirmation_email_text_enabled', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('event_id', $data ?? [], null);
        $this->setIfExists('filter_id', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('modified', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('num_tickets', $data ?? [], null);
        $this->setIfExists('num_tickets_available', $data ?? [], null);
        $this->setIfExists('num_tickets_max', $data ?? [], null);
        $this->setIfExists('num_tickets_max_per', $data ?? [], null);
        $this->setIfExists('num_tickets_sold', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('pricing_enabled', $data ?? [], null);
        $this->setIfExists('vat_category', $data ?? [], null);
        $this->setIfExists('vat_category_id', $data ?? [], null);
        $this->setIfExists('visibility_level', $data ?? [], null);
        $this->setIfExists('waiting_list_enabled', $data ?? [], null);
        $this->setIfExists('participation_certificate_credits', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAvailabilityStatusAllowableValues();
        if (!is_null($this->container['availability_status']) && !in_array($this->container['availability_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'availability_status', must be one of '%s'",
                $this->container['availability_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['num_tickets_max_per']) && (mb_strlen($this->container['num_tickets_max_per']) > 255)) {
            $invalidProperties[] = "invalid value for 'num_tickets_max_per', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['price']) && ($this->container['price'] < 0)) {
            $invalidProperties[] = "invalid value for 'price', must be bigger than or equal to 0.";
        }

        if ($this->container['vat_category_id'] === null) {
            $invalidProperties[] = "'vat_category_id' can't be null";
        }
        if (!is_null($this->container['participation_certificate_credits']) && ($this->container['participation_certificate_credits'] < 0)) {
            $invalidProperties[] = "invalid value for 'participation_certificate_credits', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets availability_status
     *
     * @return string|null
     */
    public function getAvailabilityStatus()
    {
        return $this->container['availability_status'];
    }

    /**
     * Sets availability_status
     *
     * @param string|null $availability_status Status for the availability of this ticket type. Ticket types with status \"available\", \"limited\" and \"waiting list\" are available for new participants.
     *
     * @return self
     */
    public function setAvailabilityStatus($availability_status)
    {
        if (is_null($availability_status)) {
            throw new \InvalidArgumentException('non-nullable availability_status cannot be null');
        }
        $allowedValues = $this->getAvailabilityStatusAllowableValues();
        if (!in_array($availability_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'availability_status', must be one of '%s'",
                    $availability_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['availability_status'] = $availability_status;

        return $this;
    }

    /**
     * Gets available_from
     *
     * @return \DateTime|null
     */
    public function getAvailableFrom()
    {
        return $this->container['available_from'];
    }

    /**
     * Sets available_from
     *
     * @param \DateTime|null $available_from available_from
     *
     * @return self
     */
    public function setAvailableFrom($available_from)
    {
        if (is_null($available_from)) {
            array_push($this->openAPINullablesSetToNull, 'available_from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('available_from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['available_from'] = $available_from;

        return $this;
    }

    /**
     * Gets available_to
     *
     * @return \DateTime|null
     */
    public function getAvailableTo()
    {
        return $this->container['available_to'];
    }

    /**
     * Sets available_to
     *
     * @param \DateTime|null $available_to available_to
     *
     * @return self
     */
    public function setAvailableTo($available_to)
    {
        if (is_null($available_to)) {
            array_push($this->openAPINullablesSetToNull, 'available_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('available_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['available_to'] = $available_to;

        return $this;
    }

    /**
     * Gets cancel_to
     *
     * @return \DateTime|null
     */
    public function getCancelTo()
    {
        return $this->container['cancel_to'];
    }

    /**
     * Sets cancel_to
     *
     * @param \DateTime|null $cancel_to cancel_to
     *
     * @return self
     */
    public function setCancelTo($cancel_to)
    {
        if (is_null($cancel_to)) {
            array_push($this->openAPINullablesSetToNull, 'cancel_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cancel_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cancel_to'] = $cancel_to;

        return $this;
    }

    /**
     * Gets confirmation_email_text
     *
     * @return string|null
     */
    public function getConfirmationEmailText()
    {
        return $this->container['confirmation_email_text'];
    }

    /**
     * Sets confirmation_email_text
     *
     * @param string|null $confirmation_email_text Additional text added to the confirmation email for participants. Only added when the corresponding boolean is set to True
     *
     * @return self
     */
    public function setConfirmationEmailText($confirmation_email_text)
    {
        if (is_null($confirmation_email_text)) {
            array_push($this->openAPINullablesSetToNull, 'confirmation_email_text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('confirmation_email_text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['confirmation_email_text'] = $confirmation_email_text;

        return $this;
    }

    /**
     * Gets confirmation_email_text_enabled
     *
     * @return bool|null
     */
    public function getConfirmationEmailTextEnabled()
    {
        return $this->container['confirmation_email_text_enabled'];
    }

    /**
     * Sets confirmation_email_text_enabled
     *
     * @param bool|null $confirmation_email_text_enabled True when an additional text has to be added to the confirmation email for participants
     *
     * @return self
     */
    public function setConfirmationEmailTextEnabled($confirmation_email_text_enabled)
    {
        if (is_null($confirmation_email_text_enabled)) {
            throw new \InvalidArgumentException('non-nullable confirmation_email_text_enabled cannot be null');
        }
        $this->container['confirmation_email_text_enabled'] = $confirmation_email_text_enabled;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Optional description for this ticket type
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets event_id
     *
     * @return int|null
     */
    public function getEventId()
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id
     *
     * @param int|null $event_id event_id
     *
     * @return self
     */
    public function setEventId($event_id)
    {
        if (is_null($event_id)) {
            array_push($this->openAPINullablesSetToNull, 'event_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('event_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets filter_id
     *
     * @return int|null
     */
    public function getFilterId()
    {
        return $this->container['filter_id'];
    }

    /**
     * Sets filter_id
     *
     * @param int|null $filter_id filter_id
     *
     * @return self
     */
    public function setFilterId($filter_id)
    {
        if (is_null($filter_id)) {
            array_push($this->openAPINullablesSetToNull, 'filter_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('filter_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['filter_id'] = $filter_id;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets modified
     *
     * @return \DateTime|null
     */
    public function getModified()
    {
        return $this->container['modified'];
    }

    /**
     * Sets modified
     *
     * @param \DateTime|null $modified modified
     *
     * @return self
     */
    public function setModified($modified)
    {
        if (is_null($modified)) {
            array_push($this->openAPINullablesSetToNull, 'modified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('modified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['modified'] = $modified;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name for this ticket type
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling EventTicketType., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets num_tickets
     *
     * @return int|null
     */
    public function getNumTickets()
    {
        return $this->container['num_tickets'];
    }

    /**
     * Sets num_tickets
     *
     * @param int|null $num_tickets Max. number of tickets that could be sold for this ticket type
     *
     * @return self
     */
    public function setNumTickets($num_tickets)
    {
        if (is_null($num_tickets)) {
            throw new \InvalidArgumentException('non-nullable num_tickets cannot be null');
        }
        $this->container['num_tickets'] = $num_tickets;

        return $this;
    }

    /**
     * Gets num_tickets_available
     *
     * @return mixed|null
     */
    public function getNumTicketsAvailable()
    {
        return $this->container['num_tickets_available'];
    }

    /**
     * Sets num_tickets_available
     *
     * @param mixed|null $num_tickets_available num_tickets_available
     *
     * @return self
     */
    public function setNumTicketsAvailable($num_tickets_available)
    {
        if (is_null($num_tickets_available)) {
            array_push($this->openAPINullablesSetToNull, 'num_tickets_available');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('num_tickets_available', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['num_tickets_available'] = $num_tickets_available;

        return $this;
    }

    /**
     * Gets num_tickets_max
     *
     * @return int|null
     */
    public function getNumTicketsMax()
    {
        return $this->container['num_tickets_max'];
    }

    /**
     * Sets num_tickets_max
     *
     * @param int|null $num_tickets_max num_tickets_max
     *
     * @return self
     */
    public function setNumTicketsMax($num_tickets_max)
    {
        if (is_null($num_tickets_max)) {
            array_push($this->openAPINullablesSetToNull, 'num_tickets_max');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('num_tickets_max', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['num_tickets_max'] = $num_tickets_max;

        return $this;
    }

    /**
     * Gets num_tickets_max_per
     *
     * @return string|null
     */
    public function getNumTicketsMaxPer()
    {
        return $this->container['num_tickets_max_per'];
    }

    /**
     * Sets num_tickets_max_per
     *
     * @param string|null $num_tickets_max_per num_tickets_max_per
     *
     * @return self
     */
    public function setNumTicketsMaxPer($num_tickets_max_per)
    {
        if (is_null($num_tickets_max_per)) {
            array_push($this->openAPINullablesSetToNull, 'num_tickets_max_per');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('num_tickets_max_per', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($num_tickets_max_per) && (mb_strlen($num_tickets_max_per) > 255)) {
            throw new \InvalidArgumentException('invalid length for $num_tickets_max_per when calling EventTicketType., must be smaller than or equal to 255.');
        }

        $this->container['num_tickets_max_per'] = $num_tickets_max_per;

        return $this;
    }

    /**
     * Gets num_tickets_sold
     *
     * @return int|null
     */
    public function getNumTicketsSold()
    {
        return $this->container['num_tickets_sold'];
    }

    /**
     * Sets num_tickets_sold
     *
     * @param int|null $num_tickets_sold Number of tickets that are sold for this ticket type
     *
     * @return self
     */
    public function setNumTicketsSold($num_tickets_sold)
    {
        if (is_null($num_tickets_sold)) {
            throw new \InvalidArgumentException('non-nullable num_tickets_sold cannot be null');
        }
        $this->container['num_tickets_sold'] = $num_tickets_sold;

        return $this;
    }

    /**
     * Gets price
     *
     * @return float|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param float|null $price Price for this ticket. Set to 0 to show _free_, set to null to hide price.
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            array_push($this->openAPINullablesSetToNull, 'price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($price) && ($price < 0)) {
            throw new \InvalidArgumentException('invalid value for $price when calling EventTicketType., must be bigger than or equal to 0.');
        }

        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets pricing_enabled
     *
     * @return bool|null
     */
    public function getPricingEnabled()
    {
        return $this->container['pricing_enabled'];
    }

    /**
     * Sets pricing_enabled
     *
     * @param bool|null $pricing_enabled pricing_enabled
     *
     * @return self
     */
    public function setPricingEnabled($pricing_enabled)
    {
        if (is_null($pricing_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'pricing_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pricing_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pricing_enabled'] = $pricing_enabled;

        return $this;
    }

    /**
     * Gets vat_category
     *
     * @return \Compucie\Congressus\models\VatCategory|null
     */
    public function getVatCategory()
    {
        return $this->container['vat_category'];
    }

    /**
     * Sets vat_category
     *
     * @param \Compucie\Congressus\models\VatCategory|null $vat_category vat_category
     *
     * @return self
     */
    public function setVatCategory($vat_category)
    {
        if (is_null($vat_category)) {
            throw new \InvalidArgumentException('non-nullable vat_category cannot be null');
        }
        $this->container['vat_category'] = $vat_category;

        return $this;
    }

    /**
     * Gets vat_category_id
     *
     * @return int
     */
    public function getVatCategoryId()
    {
        return $this->container['vat_category_id'];
    }

    /**
     * Sets vat_category_id
     *
     * @param int $vat_category_id vat_category_id
     *
     * @return self
     */
    public function setVatCategoryId($vat_category_id)
    {
        if (is_null($vat_category_id)) {
            array_push($this->openAPINullablesSetToNull, 'vat_category_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('vat_category_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['vat_category_id'] = $vat_category_id;

        return $this;
    }

    /**
     * Gets visibility_level
     *
     * @return string|null
     */
    public function getVisibilityLevel()
    {
        return $this->container['visibility_level'];
    }

    /**
     * Sets visibility_level
     *
     * @param string|null $visibility_level visibility_level
     *
     * @return self
     */
    public function setVisibilityLevel($visibility_level)
    {
        if (is_null($visibility_level)) {
            throw new \InvalidArgumentException('non-nullable visibility_level cannot be null');
        }
        $this->container['visibility_level'] = $visibility_level;

        return $this;
    }

    /**
     * Gets waiting_list_enabled
     *
     * @return bool|null
     */
    public function getWaitingListEnabled()
    {
        return $this->container['waiting_list_enabled'];
    }

    /**
     * Sets waiting_list_enabled
     *
     * @param bool|null $waiting_list_enabled waiting_list_enabled
     *
     * @return self
     */
    public function setWaitingListEnabled($waiting_list_enabled)
    {
        if (is_null($waiting_list_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'waiting_list_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('waiting_list_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['waiting_list_enabled'] = $waiting_list_enabled;

        return $this;
    }

    /**
     * Gets participation_certificate_credits
     *
     * @return float|null
     */
    public function getParticipationCertificateCredits()
    {
        return $this->container['participation_certificate_credits'];
    }

    /**
     * Sets participation_certificate_credits
     *
     * @param float|null $participation_certificate_credits Number of credits for the participation certificate. Set to 0 to disable certificate. Set to null to use the default value from the event.
     *
     * @return self
     */
    public function setParticipationCertificateCredits($participation_certificate_credits)
    {
        if (is_null($participation_certificate_credits)) {
            array_push($this->openAPINullablesSetToNull, 'participation_certificate_credits');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('participation_certificate_credits', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($participation_certificate_credits) && ($participation_certificate_credits < 0)) {
            throw new \InvalidArgumentException('invalid value for $participation_certificate_credits when calling EventTicketType., must be bigger than or equal to 0.');
        }

        $this->container['participation_certificate_credits'] = $participation_certificate_credits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


